version: "3.8"

services:
  postgresql:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgress"
      POSTGRES_DB: "bookstore"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "bookstore", "-U", "postgres" ]
      interval : 5s
      timeout : 5s
      retries : 5

  backend-api:
    build: ./backend-api
    ports:
      - "8000:8000"
    environment:
      POSTGRES_SERVER: "postgresql"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgress"
      POSTGRES_DB: "bookstore"
      POSTGRES_PORT: "5432"
    depends_on:
      postgresql:
        condition: service_healthy

  frontend:
    build: ./Book-tracking-app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_API_URL: http://backend-api:8000 
